### ISSUE TITLE
Can't get authentication from injected SecurityService in a chain after calling a micronaut-data repository method

### ISSUE THREAD

**Issue by fdittz** [micronaut-projects/micronaut-security#1468]
### Expected Behavior

We should be able do inject SecurityService outside of a controller: https://micronaut-projects.github.io/micronaut-security/latest/guide/#securityService

### Actual Behaviour

When we inject SecurityService into a bean and invoke a method of this bean after calling any micronaut-data repository method, SecurityService gets successfully injected, however getAuthentication will return null.

Example - calling a repository .count() method and then calling findByResourceId in a ResourceReactorRepositoryAdapter, which has SecurityService injected:

```
public Mono<ResourceEntity> executeAfterRepositoryMethod(ResourceEntity resource) {
        LOGGER.info("securityService.getAuthentication().isPresent(): {}", securityService.getAuthentication().isPresent());
        return resourceRepository.count()
                .flatMap(res -> resourceReactorRepositoryAdapter.findByResourceId(resource.getResourceId())).then(Mono.just(resource));
    }
```

If we however call resourceReactorRepositoryAdapter.findByResourceId(resource.getResourceId()) without a preceding  repository call, securityService.getAuthentication() will return an Authentication instance as expected

Example:
```
public Mono<ResourceEntity> execute(ResourceEntity resource) {
        LOGGER.info("securityService.getAuthentication().isPresent(): {}", securityService.getAuthentication().isPresent());
        return resourceReactorRepositoryAdapter.findByResourceId(resource.getResourceId());
    }
```

And the ResourceReactorRepositoryAdapter class, where the issue happens:

```
@RequiredArgsConstructor
@Singleton
public class ResourceReactorRepositoryAdapter implements ResourceRepository {

    private final ResourceReactorCrudRepository resourceReactorCrudRepository;
    private final SecurityService securityService;
    private static final Logger LOGGER = LoggerFactory.getLogger(ResourceReactorRepositoryAdapter.class);


    @Override
    public Mono<ResourceEntity> findByResourceId(String id) {
        LOGGER.info("securityService.getAuthentication().isPresent(): {}", securityService.getAuthentication().isPresent());
        return resourceReactorCrudRepository
                .findByResourceId(id);
    }
}
```
By debugging internally, seems that somehow the request is not being propagated after a repository method is called in the same chain.

I don't know if it's really a bug or if it is an issue with micronaut-security or micronaut-data. Same thing happens using either hibernate-reactive or R2DBC

### Steps To Reproduce

Please use the example app, which is a subset of our project.
It uses testcontainers to put up a mysql instance.

In the project's root directory there's a insomnia collection (insomnia-requests.json) with two requests, with a dummy application (id/secret) that I've created on auth0 for this purpose.

By calling the "Create  Resource" request (/api/resource) you should see the authentication being correctly retrieved in ResourceReactorRepositoryAdapter, identified by this log message:
```
INFO c.a.i.d.a.ResourceReactorRepositoryAdapter - securityService.getAuthentication().isPresent(): true
```

If you call "Create Resource - Repository in chain" (/api/resource/repository) you can reproduce the issue, identified by this log message:
```
INFO  c.a.i.d.a.ResourceReactorRepositoryAdapter - securityService.getAuthentication().isPresent(): false
```

I'm using .count() as the repository method for the sake of simplicity, but it happens with any repository method I call.
Dont mind the 404 returned, it's expected.

### Environment Information

Ubuntu 22.04
Amazon Corretto 17

### Example Application

https://github.com/fdittz/authentication-issue

### Version

4.1.4

**Comment by sdelamo** [comment]
Probably related to the changes to [context propagation](https://docs.micronaut.io/latest/guide/#contextPropagation) in Micronaut Framework 4

**Comment by jeremyg484** [comment]
@fdittz Thanks for providing the sample!

@sdelamo is right in that this is related to the new context propagation API. 

In this particular case, the problem is caused by Hibernate Reactive using its Vert.x based reactive database driver, which creates its own Netty event loop that is distinct from the main Micronaut event loop. This results in thread context switching during the course of processing a request, and that is exactly what is happening here. If you have your log statements set up to include the current thread ID, you'll notice that when `securityService.getAuthentication().isPresent()` returns `false`, the code is being executed on a Vert.x thread.

The quick fix is to include the Micrometer Context Propagation dependency as described in the [context propagation](https://docs.micronaut.io/latest/guide/#contextPropagation) docs. To do so, add:

```
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>context-propagation</artifactId>
</dependency>
```

to your pom.xml.

I realize it may seem counter-intuitive if you aren't using Micrometer, but this dependency takes care of instrumenting Reactor such that the reactive context is propagated appropriately, in this case from the Micronaut event loop to the Vert.x event loop.

**Comment by sdelamo** [comment]
Created https://github.com/micronaut-projects/micronaut-starter/issues/2216 and https://github.com/micronaut-projects/micronaut-reactor/issues/384
