### ISSUE TITLE
Set a default expiration for refresh tokens

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-security#175]
At this moment the refresh tokens never expires by default: https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/JwtGeneratorConfigurationProperties.java#L38

It would be good to set an expiration time by default as we do with access tokens. Probably it makes sense to define a little bit longer than the default expiration time for the access tokens.

**Comment by sdelamo** [comment]
You can set an expiration for refresh tokens `micronaut.security.token.jwt.generator.refresh-token-expiration` with seconds.

**Comment by alvarosanchez** [comment]
I think the point Iván is trying to make is that there should be a **default** expiration.

**Comment by ilopmar** [comment]
Yes, that what I was trying to say!

**Comment by jameskleeh** [comment]
@ilopmar What would be a sensible default? Why do you think never expiring is not a sensible default?

**Comment by ilopmar** [comment]
I think a sensible default for the refresh token is to expire a little bit later than the access token, so the users can use it for refresh the credentials.
Having in mind than a lot of users won't modify the defaults, I think it is better not to have tokens that never expire. As this is about security I think it's better to be more conservative about the defaults.

**Comment by alvarosanchez** [comment]
We should conclude #174 before making a decision here.

For example, in Google refresh tokens never expire, but they do have a revocation list to check, so that if a user removes access for an application, this application's refresh token will not work any more.

In my opinion, what it should be done is:

1. Keep refresh token expiration unset.
2. Make sure the refresh token isn't granted any roles/scopes as if it were an access token.
3. Add generic support for checking whether a token (both access and refresh) has been revoked, possibly with an interface, leaving to the users the responsibility of implementing it.

**Comment by phillwatson** [comment]
io.micronaut.security.token.jwt.cookie.JwtCookieLoginHandler
Uses the same configuration (including max-age) for both access-token and refresh-token. There doesn't appear to be a way of specifying the refresh-token should not expire.
