### ISSUE TITLE
Security-session only looks for old config

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-security#261]
```
@Configuration
@Requires(property = SecuritySessionConfigurationProperties.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
package io.micronaut.security.session;
```

If someone moves to the new config and sets `authentication = cookie`, with security-session on the classpath, session related beans will still override

**Comment by sdelamo** [comment]
Not sure if I am understand. 

If you have both `security-jwt` and `security-session`. 

If you have `micronaut.micronaut.authentication: cookie'. 

`SecuritySessionLoginHandler` will not be loaded because the class will be annotated with [`@Requires(property = SecurityConfigurationProperties.PREFIX + ".authentication", value = "session")`](https://github.com/micronaut-projects/micronaut-security/blob/master/security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java#L45)

The `@Configuration` you mention will disable every session bean if you want that.
