### ISSUE TITLE
Throw an error when 2 or more security annotations are applied to a method

### ISSUE THREAD

**Issue by frinka** [micronaut-projects/micronaut-security#28]
Discovered this during @sdelamo deep dive presentation. If you add `@Secured` and `@RolesAllowed`, the method will use the first annotation found. Instead, it should throw an error to let the developer know that only one annotation is supported.

Example:
```
    @Secured(SecurityRule.IS_AUTHENTICATED)
    @View("books")
    @Get
    @RolesAllowed("ROLE_USER")
    public Map<String, Object> index() {
        Map<String, Object> model = new HashMap<>();
        model.put("books", Arrays.asList(new Book("1491950358", "Building Microservices"),
        new Book("1680502395", "Release It!"),
        new Book("0321601912", "Continuous Delivery")));
        return model;
    }

```

**Comment by alvarosanchez** [comment]
This issue can't be solved unless https://github.com/micronaut-projects/micronaut-core/issues/2644 is implemented,

**Comment by trumank-il** [comment]
This issue is still occurring in version 4.2.1 and is silently ignoring security configurations that prevent unwanted access. An error would be ideal, however at least updating the documentation to warn against using both annotations would be appropriate: https://micronaut-projects.github.io/micronaut-security/latest/guide/#secured

**Comment by sdelamo** [comment]
@trumank-il I have created a [PR to document it](https://github.com/micronaut-projects/micronaut-security/pull/1833). Thanks for leaving the comment.
