### ISSUE TITLE
AbstractSecurityRule#getRoles adds mutually exclusive roles

### ISSUE THREAD

**Issue by LGalabov** [micronaut-projects/micronaut-security#629]
Hi guys,

I was reading through the library classes and I believe the _getRoles()_ method of class _AbstractSecurityRule_ is adding mutually exclusive roles to the _roles_ list.

If the _claims_ map is not _null_, its content (nothing if empty) plus _IS_ANONYMOUS_ and _IS_AUTHENTICATED_ are added to the result.
I don't have broad knowledge of how Micronaut's security rules work, but it seems that the user is anonymous only if the _claims_ map is _null_, so _IS_ANONYMOUS_ should not be added in the second branch.

[AbstractSecurityRule.java#L66](https://github.com/micronaut-projects/micronaut-security/blob/aade741380a4a50dfc4ab120a6a15469c84b0c37/security/src/main/java/io/micronaut/security/rules/AbstractSecurityRule.java#L66)

I created this issue because I didn't know how to report my observation, so feel free to close it if you find I am wrong.

Thanks and keep it up!

**Comment by sdelamo** [comment]
I think the problem is `IS_ANONYMOUS` is not a great name. 

If you secure your controller with `@Secured(SecurityRules.IS_ANONYMOUS)` is the same as if you used `@PermitAll`. That it is to say authenticated users or users who are not authenticated will be able to access that resource. That it is the reason of the logic you highlight.

**Comment by LGalabov** [comment]
Ok, now it makes sense. Thanks! :)
